export const dummySkills: SkillRecord[] = [
	{
		id: "skill_001",
		title: "Write Clean TypeScript",
		slug: "write-clean-typescript",
		description:
			"Learn practical patterns for readable, maintainable TypeScript code.",
		category: "Programming",
		tags: ["typescript", "clean-code", "best-practices"],
		installCommand: "npx @skills/install write-clean-typescript",
		createdAt: "2026-04-20T10:15:00.000Z",
		authorClerkId: "user_clerk_001",
		authorEmail: "author1@example.com",
	},
	{
		id: "skill_002",
		title: "Build Responsive UI",
		slug: "build-responsive-ui",
		description: "Create responsive layouts using modern CSS techniques.",
		category: "Frontend",
		tags: ["css", "responsive", "ui"],
		installCommand: "npx @skills/install build-responsive-ui",
		createdAt: "2026-04-21T12:30:00.000Z",
		authorClerkId: "user_clerk_002",
		authorEmail: "author2@example.com",
	},
	{
		id: "skill_003",
		title: "Master React Hooks",
		slug: "master-react-hooks",
		description:
			"Understand and apply core and custom React hooks effectively.",
		category: "React",
		tags: ["react", "hooks", "state-management"],
		installCommand: "npx @skills/install master-react-hooks",
		createdAt: "2026-04-22T08:45:00.000Z",
		authorClerkId: "user_clerk_003",
		authorEmail: "author3@example.com",
	},
	{
		id: "skill_004",
		title: "Design REST APIs",
		slug: "design-rest-apis",
		description: "Design consistent and scalable REST API endpoints.",
		category: "Backend",
		tags: ["api", "rest", "backend"],
		installCommand: "npx @skills/install design-rest-apis",
		createdAt: null,
		authorClerkId: null,
		authorEmail: null,
	},
	{
		id: "skill_005",
		title: "Optimize Web Performance",
		slug: "optimize-web-performance",
		description: "Improve page speed and runtime performance for web apps.",
		category: "Performance",
		tags: ["performance", "optimization", "web-vitals"],
		installCommand: "npx @skills/install optimize-web-performance",
		createdAt: "2026-04-25T16:00:00.000Z",
		authorClerkId: "user_clerk_005",
		authorEmail: "author5@example.com",
	},
];
